// src/components/Card.vue
<script setup lang="ts">
import type { Card } from '../types'

defineProps<{
  card: Card
  hidden?: boolean
}>()
</script>

<template>
  <div 
    class="card transform transition-all duration-200 hover:scale-105" 
    :class="{ 
      'bg-gray-300': hidden, 
      'bg-white': !hidden,
      'shadow-lg': !hidden,
      'shadow-md': hidden
    }"
  >
    <template v-if="!hidden">
      <div :class="[
        'text-2xl font-bold',
        card.suit === '♥' || card.suit === '♦' ? 'text-red-500' : 'text-gray-800'
      ]">
        {{ card.rank }}
        <span class="text-3xl">{{ card.suit }}</span>
      </div>
    </template>
  </div>
</template>

// card.tsx
import React from 'react';
import { Card as CardType } from './types';

interface CardProps {
  card: CardType;
  hidden?: boolean;
}

export const Card: React.FC<CardProps> = ({ card, hidden = false }) => {
  const { suit, rank } = card;
  const color = suit === '♥' || suit === '♦' ? 'text-red-500' : 'text-black';

  return (
    <div className={`w-16 h-24 rounded-lg shadow-md flex items-center justify-center ${hidden ? 'bg-gray-300' : 'bg-white'}`}>
      {!hidden && (
        <div className={`text-2xl font-bold ${color}`}>
          {rank}
          <span className="text-3xl">{suit}</span>
        </div>
      )}
    </div>
  );
};
